fix: return errors from fastify route handlers
ts-rest/ts-rest pull request #326
Opened 2023-07-31 04:02 UTC by suphon-t

`requestValidationErrorHandler` currently only handles `RequestValidationError` while silently consuming all other errors. This means that if there is any unhandled error in a route handler, the request never completes.

I added a test case for demonstration, and fixed the issue by re-throwing errors other than `RequestValidationError`.

2023-07-31 18:10 UTC, gustawdaniel requested changes

2023-07-31 18:10 UTC, gustawdaniel commented on libs/ts-rest/fastify/src/lib/ts-rest-fastify.ts
> +      throw err;
I receiving here

```
http: LogLevel.ERROR: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing a GET request to URL: http://localhost:4000/
```

I prefer to get 500 with error message or even better be able to override it by my own handler.

2023-07-31 18:13 UTC, gustawdaniel approved these changes

2023-08-05 00:56 UTC, michaelangelo-io approved these changes
LGTM!

2023-08-05 00:57 UTC, michaelangelo-io commented
Can you add a changeset bump to the fastify package @suphon-t?

2023-08-06 17:36 UTC, merged